### ISSUE TITLE
diploid mode option in version 180114

### ISSUE THREAD

**Issue by wangwl** [aidenlab/3d-dna#10]
Hi,
Thanks for the great work! But it seems that the "diploid" variable remained "false" even a "-m diploid" option is given in the new version.

Best,
Wenliang

**Comment by dudcha** [comment]
Hi Wenliang,

Oops, thanks for the catch. Committed fix. In general (as you might have guessed!) we have not run as much the updated version in diploid mode, so any feedback you have would be extremely helpful!

Thanks again!
Olga

**Comment by wangwl** [comment]
Hi Olga,
Thanks for the response.

There is another bug:  in "merge-tiled-asm.sh" the filename is still "reverse-single-fasta.awk" while in "utils" directory it's "reverse-fasta.awk".

And I also have a confusion:  in the old version, the polish step is only for diploid mode, while in the new version it's applied to both mode, could you tell me why? Have you done any other revisions for diploid mode?

Lastly, one suggestion:  there is no visualization file generated for the final result of diploid mode. It would be better if that is in the pipeline.

Thanks,
Wenliang

**Comment by dudcha** [comment]
Hi Wenliang,

This i to let you know that there is a preliminary update to merge here: https://github.com/theaidenlab/AGWG-merge if you want to give it a try. I expect we will merge it with the main branch soon.

Olga

**Comment by dudcha** [comment]
P.S. This is now part of the main branch. Reverse-fasta.awk script is a generalization to reverse-single-fasta.awk and i deed substitutes.

With respect to the visualization for diploid mode there are track files for this, and there are, I believe, considerable improvements in this specific aspect in the updated version of the pipeline. Note that it is not very easy to build a contact map after merging as this is no longer about just lifting the coordinates of previously aligned reads like for ordering and orientation changes: the reads as a rule need to be realigned.
