### ISSUE TITLE
The produced hic file by run-asm-pipeline.sh is only 400k

### ISSUE THREAD

**Issue by hyliu87** [aidenlab/3d-dna#103]
Hi ,
I run 3d-dna for a 2.1g genome with the command: ./run-asm-pipeline.sh -r 2 genome.fa aligned/merged_nodups.txt, but the produced hic file is only 400k, while the first step juicer.sh generated hic is 2.1g. What is wrong?

Thank you

**Comment by dudcha** [comment]
Hello Hayliu,

You will need to examine the error messages: There is no way to meaningfully comment from your message along.

Best,
Olga
