### ISSUE TITLE
Disk quota exceeded with 2Tb of available memory

### ISSUE THREAD

**Issue by CristinaAS** [aidenlab/3d-dna#104]
Hello! I've been trying to run the run-asm-pipeline.sh with a 46Gb merged_nodups.txt file as input. It generated almost 4200 itinerations in round 0 of scaffolding and it stopped because the disk quota was exceeded. I left almost 2Tb of available space and was still not working. I tried several times after filtering the initial genome and, in the final trial, the merged_nodups.txt file was reduced to 34Gb and after 2826 itinerations (almost half less than the first time) it stopped because of the disk quota was exceeded again.
Is there a way to simplify the number of generated itinerations in order to save memory? Do you have any idea of what can be happening in this analysis? 

Many thanks,
Cristina

**Comment by dudcha** [comment]
Hello Cristina,

How many pieces is your assembly? 4200 is a lot of iterations, but this should not matter all that much. Your merged_nodups is not all that big. Regardless, the merged_nodups is not modified or copied during the iterations so in itself this should not result in it out of space error. In each iteration the size should increase by a size of a text file that describes the order and orientation of the pieces. Even it is is ~1Mb (that would be a lot of pieces) that would still be ~4Gb overall space, nowhere near 2Tb. Check if you are actually writing these where you think you are writing, and not to some other disk.

Olga

**Comment by CristinaAS** [comment]
My assembly has 48274281 contigs (I don't know if there is a maximum of pieces). 
I running the pipeline in the same conditions that other analysis that worked fine so it may be a problem related with the genome I'm using now.

Many thanks,
Cristina

**Comment by CristinaAS** [comment]
My assembly has 106,548 contigs (I don't know if there is a maximum of pieces).
I'm running the pipeline in the same conditions that other analysis that worked fine so it may be a problem related to the genome I'm using now.

Many thanks,
Cristina

**Comment by CristinaAS** [comment]
My assembly has 106,548 contigs (I don't know if there is a maximum of pieces).
I'm running the pipeline in the same conditions that other analysis that worked fine so it may be a problem related to the genome I'm using now.

Many thanks,
Cristina

**Comment by dudcha** [comment]
Hi Cristina,

There is no explicit maximum for the number of pieces. Unfortunately I cannot offer any help with the info that you have shared. Sorry,

Olga

**Comment by lifan18** [comment]
Hi guys,

Good day! I have the same problem about disk quota exceeded with more than 5 Tb available. Could you help me to fix this?

Please see the details as the following,

```
M::mem_pestat] low and high boundaries for proper pairs: (1, 18986)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 1333334 reads in 401.364 CPU sec, 401.403 real sec
[fputs] Disk quota exceeded
Not sure how to parse your input: files not listed or not found at expected locations. Exiting!

*****************************************************
3D de novo assembly: version 180114
```
```
                         Block Limits                                   
Filesystem type         blocks      quota      limit   in_doubt    grace
gpfs       USR          6.746T        12T        12T       544M     none
```
Thank you all!

Best
