### ISSUE TITLE
Java error with specific contigs

### ISSUE THREAD

**Issue by DustinSokolowski** [aidenlab/3d-dna#108]
Hello!

Thank you for your great tool. I am trying to apply the 3d-dna pipeline to a trio-binned de novo genome assembly. 

I tiro-binned with TrioCanu and then assembled with flye. I then generated the merged_nodups.txt file with juicer. When I run the 3d-dna pipeline on the maternal/paternal genomes, I am unable to generate .hic files and it seems to reject certain scaffolds.

command:

```
run-asm-pipeline.sh  -m "haploid" -i 10000 paternal/bwa_index/assembly.fasta aligned/merged_nodups.txt
```

Merged nodups is 145Gb in size and 99.8% the size of merged_sort.

The error that is being thrown is shown below. The same contig has an issue if I use "diploid". This scaffold is 16Kb in length, The exact same error is thrown in the maternal 3d-dna but for a different scaffold which is 450Kb. Interestingly, When I used the combined genome (i.e. no Trio-Binning step), 3d-DNA seems to run just fine. For a Trio-binned genome are there extra steps required before juicer/3d-dna? Otherwise have you seen this issue before?

![image](https://user-images.githubusercontent.com/56414662/112736613-789ebf00-8f2a-11eb-9e5e-b2e221d7ab02.png)

**Comment by dudcha** [comment]
Hello Dustin,

My guess is that there is some problem with your merged_nodups. Is this the proper 12-file format? The 3d-dna never actually builds maps in terms of original contigs, so it should never even see the "contig_669" string if all is correct. I'd double-check the input.

Olga

**Comment by DustinSokolowski** [comment]
Hey Olga,

Thank you for your answer. Is there a way of checking if the file is the proper 12 file format? I've attached the first 1000 lines of mergerd_nodups as well as mreged_nodups that contain the scaffold that seems to be having an issue.

Best!
Dustin
[merged_1k.txt](https://github.com/aidenlab/3d-dna/files/6231163/merged_1k.txt)
[merged_1k_contig.txt](https://github.com/aidenlab/3d-dna/files/6231164/merged_1k_contig.txt)

**Comment by dudcha** [comment]
16-field format actually. This piece at least looks fine to me. You can do some awk one liner saying something like awk ‘NR!=16’ path to mnd file to check the rest.

Olga

**Comment by DustinSokolowski** [comment]
Hey!

Thank you so much! Excellent catch. There was a single line where there weren't missing fields and it was from the correct contig.

![image](https://user-images.githubusercontent.com/56414662/113071085-06c8ae80-9192-11eb-9955-212eb58194b5.png)

I was using the PBS version of juicer which is still in it's beta version so perhaps something carried over strangely there. I'll add `awk 'NF==16' merged_nodups.txt > merged_nodups.txt` to my pipeline and it should be good!

Best,
Dustin

**Comment by dudcha** [comment]
This will ignore problematic lines but I’d investigate the reason: the corrupt mnd suggests you have some issues when running juicer, before you ever start 3d-dna. -Olga

**Comment by DustinSokolowski** [comment]
That makes a lot of sense. ! I'll continue to look into it. 
Thanks again!
Dustin
