### ISSUE TITLE
gawk: fatal error: internal error

### ISSUE THREAD

**Issue by hhd1008611** [aidenlab/3d-dna#109]
Hello! I've been trying to run the run-asm-pipeline.sh with 2.5Gb TT1_3.wrap.fa and 38Gb merged_nodups.txt file as input.

**Command:**

	run-asm-pipeline.sh TT1_3.wrap.fa merged_nodups.txt

**My Prerequisites:**

	  LastZ version 1.04.00 released 20170312
	  Java openjdk version "1.8.0_92"
	  GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
	  GNU Awk 4.1.4, API: 1.1 (GNU MPFR 3.1.5, GNU MP 5.1.2)
	  sort (GNU coreutils) 8.31
	  Python 2.7.16 :: Anaconda, Inc.
	  scipy v1.6.1 numpy v1.19.2 matplotlib v3.3.4
	  GNU Parallel v20210222

**Error:**

	  gawk: /public/home/wanglei/software/3d-dna/scaffold/generate-unsorted-confidence-table.awk:131: (FILENAME=h.scores.step.1.txt FNR=239912) fatal error: internal error
	  awk: /public/home/wanglei/software/3d-dna/edit/overlay-edits.awk:47: (FILENAME=suspect.at.step.0.bed FNR=1) fatal error: internal error
	  awk: /public/home/wanglei/software/3d-dna/edit/overlay-edits.awk:47: (FILENAME=TT1_3.wrap.resolved.polish.mismatch_narrow.bed FNR=1) fatal error: internal error
	  awk: /public/home/wanglei/software/3d-dna/split/overlay-edits.awk:27: (FILENAME=TT1_3.wrap.polished_asm.scaffold_track.txt FNR=2) fatal: division by zero attempted
	  :| Warning: no explicit bundle size was listed. Will use the same one as listed for false positive size threshold: this is the most typical scenario.
	  awk: /public/home/wanglei/software/3d-dna/seal/seal-assembly.awk:180: (FILENAME=TT1_3.wrap.split.assembly FNR=2710) fatal error: internal error
	  /public/home/wanglei/software/3d-dna/seal/run-assembly-sealer.sh: line 68: 23869 Aborted                 (core dumped) awk -v size=${SIZE} -v bundle=${BUNDLE} -f ${pipeline}/seal/seal-assembly.awk ${current_assembly} > ${id}.sealed.assembly
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-mnd-according-to-new-cprops.awk:24: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  :| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
	  :| Warning: No input for label2 was provided. Default for label2 is ":::debris"
	  awk: /public/home/wanglei/software/3d-dna/edit/edit-fasta-according-to-new-cprops.awk:28: fatal: cannot open file `TT1_3.wrap.rawchrom.cprops' for reading (No such file or directory)
	  Files corresponding to original input not found. Exiting!
	  awk: fatal: cannot open file `TT1_3.wrap.final.no_overhangs.cprops' for reading (No such file or directory)
	  awk: fatal: cannot open file `TT1_3.wrap.final.no_overhangs.asm' for reading (No such file or directory)
	  cp: cannot stat 'TT1_3.wrap.final.no_overhangs.cprops': No such file or directory
	  cp: cannot stat 'TT1_3.wrap.final.no_overhangs.fasta': No such file or directory
	  rm: cannot remove 'TT1_3.wrap.final.no_overhangs.cprops': No such file or directory
	  rm: cannot remove 'TT1_3.wrap.final.no_overhangs.asm': No such file or directory
	  rm: cannot remove 'TT1_3.wrap.final.no_overhangs.fasta': No such file or directory

I changed to another version of AWK, but I got the same error. Do you know what happened in the process?

Many thanks
Lei Wang

**Comment by dudcha** [comment]
Hello Lei,

Does not seem to do anything with the pipeline, maybe this thread may be of help: http://computer-programming-forum.com/11-awk/99841de1895b0192.htm

Best,
Olga
