### ISSUE TITLE
Super slow when output fasta file

### ISSUE THREAD

**Issue by xinghua1001** [aidenlab/3d-dna#110]
Hi,

The program gets super slow every time it tries to output a fasta file.

Some others mentioned that it is due to edit-fasta-according-to-new-cprops.awk.

I am not good at coding, however.  Are there any solutions or modifications to the code?

**Comment by dudcha** [comment]
Wrap your fasta before passing it to 3d-dna (utils/wrap-fasta.awk). Best, -Olga

**Comment by tiramisutes** [comment]
> Wrap your fasta before passing it to 3d-dna (utils/wrap-fasta.awk). Best, -Olga


Can you give a detailed explanation that how to wrap the fasta file? The `edit-fasta-according-to-new-cprops.awk` script is really too slow. I have tried to use `parallel --pipe` as follows. But it doesn't seem to work.
```
parallel --pipe awk -f ${pipeline}/edit/edit-fasta-according-to-new-cprops.awk ${genomeid}.final.cprops ${orig_fasta} > ${genomeid}.final.fasta
```
Thanks.

**Comment by dudcha** [comment]
awk utils/wrap-fasta.awk original.fasta > wrapped.fasta

Pass wrapped fasta in places of the original.

Olga

**Comment by tiramisutes** [comment]
Thanks. I got it.

**Comment by ld9866** [comment]
Hello! 
Is that useful to "Pass wrapped fasta in places of the original"？
Thank you!

**Comment by dudcha** [comment]
Yes, the wrapped fasta is usually much faster. This is coded to be done automatically in recent commits. -Olga

**Comment by ld9866** [comment]
OK! Thank you very much for your reply. I have now completed this step and started a new attempt.

**Comment by JiantaoZhao426** [comment]
Is it possible to rewrite this step in order to use multiple threads?

**Comment by Innocent-L** [comment]
Will the wrapped fasta need to be used in the final review or start using 3d-dna？
 thanks
-L

> OK! Thank you very much for your reply. I have now completed this step and started a new attempt.

**Comment by ld9866** [comment]
on the start using 3d-dna, after the wrapped step the time in 3d-dna will be quicker.

**Comment by Innocent-L** [comment]
> on the start using 3d-dna, after the wrapped step the time in 3d-dna will be quicker.

thanks very very.  I will try it.
