### ISSUE TITLE
My .hic map doesn't load onto Juicerbox

### ISSUE THREAD

**Issue by cgy0627** [aidenlab/3d-dna#112]
Hello,

I have .hic outputs from both haplotid and diplotid options, but neither of them loads onto Juicebox. The online Juicebox tells me "Error loading [object File]: RangeError: Offset is outside the bounds of the DataView", and the Windows Juicebox simply says "Error loading .hic file".

What could be wrong with my files?

Thanks,
Jenny

**Comment by dudcha** [comment]
Hi Jenny,

Were you able to resolve this? My guess that your files are just empty. Check the log for the files, or simply look at the size. A typical .hic is some number of Mb in size. If you are seeing a few kb, that means it's empty. -Olga

**Comment by jiangshan529** [comment]
> Hi Jenny,
> 
> Were you able to resolve this? My guess that your files are just empty. Check the log for the files, or simply look at the size. A typical .hic is some number of Mb in size. If you are seeing a few kb, that means it's empty. -Olga

Hi, Olga. I have a .hic file with 15Gb size, but still has the same problem.
