### ISSUE TITLE
ERROR - tail: invalid number of bytes: ‘+’

### ISSUE THREAD

**Issue by cgy0627** [aidenlab/3d-dna#113]
Hello,

I ran 3D-DNA using the diploid option but it ends with a long list of following errors:
tail: invalid number of bytes: ‘+’
tail: invalid number of bytes: ‘+’
tail: invalid number of bytes: ‘+’
tail: invalid number of bytes: ‘+’

Does 3D-DNA generate a log file with all the standard outputs? Since I haven't saved the logs separately, I am unable to view any possible errors that has occurred before the long list of tail errors.

Any help would be greatly appreciated.

Thanks,
Jenny

**Comment by dudcha** [comment]
Hi Jenny,

You can save the logs forwarding the error stream to whatever file you want (2>log.txt). Diploid version has not been supported for a while now, sorry. I would not advise you to use it unless you absolutely need to. If you see evidence of undercollapsed heterozygosity in .0.hic map it may be easier to go back and run somethign like purge haplotigs on the draft and rerunning the Hi-C data alignment etc. There are some cases where you really need to purge locally, and if this is one of those cases I would refer to the AGWG freeze (github agwg-merge).

Hope this helps,
Olga
