### ISSUE TITLE
Broken pipe in finalize step - 2. Make a dd insertion

### ISSUE THREAD

**Issue by DustinSokolowski** [aidenlab/3d-dna#117]
Hey!

Thank you for your great too. I am having the same problem as issue #24 (Broken Pipeline in 'finalize' step #29). Your solution to this was to add a dd insertion to lines 62 and 64 of construct-fasta-from-asm.sh. After some googling I was unable to figure out what a dd insertion is. Is there any chance that you could respond with the code that you had in mind so I can make the correct changes without having to guess/check?

I saw that on your google group discussion , that you wanted the two lines replaced with the following:

Line 62: `tail -c +${index[${contig}]} ${fasta} | awk '$0~/>/{exit}1' | awk -f ${pipeline}/utils/reverse-fasta.awk -`
Line 64: `tail -c +${index[${contig}]} ${fasta} > tmp.fasta && awk '$0~/>/{exit}1' tmp.fasta | awk -f ${pipeline}/utils/reverse-fasta.awk`

This conversation was a couple years ago and I noticed that while line 62 looks like the line 62 you wanted changed, line 64 does not. Is this due to a system specific issue and I should replace the line 64? I have 3d-dna/20210216.

Thanks so much!
Dustin 

Github issue: https://github.com/aidenlab/3d-dna/issues/29
Google group Discussion: (https://groups.google.com/g/3d-genomics/c/cqAmJHbXCzE/m/M3B--B8RBAAJ)

**Comment by dudcha** [comment]
Hi Dustin,

You sure that the source of the problem is the same though? A much more common source of this problem is when folks use the wrong assembly file when running post-review step or, somewhat more rarely, there are some weird characters like carriage return in fasta.

Best,
Olga

**Comment by DustinSokolowski** [comment]
Hey Olga!

I'm not certain if that is the source of the problem. This being said, I doubt that I am using the wrong assembly file when running the post-review step as I'm using the run-asm-pipeline function which should use the same assembly file all the way though. Is there a way of checking for these weird characters in the fasta?

I have attached an overview of what I did below:

I assembled my nanopore genome with Flye.

`flye --nano-raw fastq/male.fastq.gz --out-dir male --genome-size 2700m --threads 16`

I aligned Hi-C reads with juicer2.0-CPU. It worked successfully until the postprocessing step because the two file sizes below were equal in size:

`	size1=$(samtools view $sthreadstring -h ${outputdir}/merged_sort.bam | wc -l | awk '{print $1}')`
`	size2=$(wc -l ${outputdir}/merged_dedup.sam | awk '{print $1}')`

I also converted the deduplicated bam file back to a merged_nodups file with Neva's script
`samtools view -O SAM -F 1024 merged_dedup.sam | awk -v mnd=1 -f $juicedir"common/"sam_to_pre.awk > merged_nodups.txt`

I then ran 3d-DNA using close to default parameters.

`run-asm-pipeline.sh  -m "haploid" -i 10000 /dir/assembly.fasta /align/merged_nodups.txt`

Best,
Dustin

**Comment by dudcha** [comment]
Do you mind sharing the full stdout/stderr if you have it?

For carriage return one can open in something that can show them (https://superuser.com/questions/409919/cr-and-lf-characters-shown-at-the-end-of-each-line-in-notepad)

or do something like tr '\r' '\n' < file > mod_file

and see there’s any difference.

Another thing to check that one user once had is that they had empty lines in the fasta, also probably some conversion or newline characters problem.

Best,
Olga

**Comment by DustinSokolowski** [comment]
Hey!

Here are the files. I switched from the diploid to the haploid version between runs as it was reccomended and possible an issue. With that in mind these are the stdout and stderr of the same script but diploid. it's haploid equivalent should be ready in the next day or so.

I'll check the file/empty line differences ASAP

Best,
Dustin
[stderr.txt](https://github.com/aidenlab/3d-dna/files/6402107/stderr.txt)
[stdout.txt](https://github.com/aidenlab/3d-dna/files/6402108/stdout.txt)

Edit: I checked what else you suggested. there is no difference and there are no empty lines :)

**Comment by dudcha** [comment]
I don’t see anything bad happening with the pipeline up to the finalize part. If you are happy with the rawchrom.hic just run the post-review with -r rawchrom.assembly to do the very last part (in haploid will be the default) to save some time, no need to rerun the whole pipeline. -Olga

**Comment by DustinSokolowski** [comment]
Hey Olga,

Thanks so much! you're right -- the code I adjusted and switching to haploid didn't do the trick. May I send the stdout and stderr of the finalize portion once it's run?

Best,
Dustin

**Comment by DustinSokolowski** [comment]
Hey Olga,

Running the `run-asm-pipeline-post-review.sh` with the following script below:
`run-asm-pipeline-post-review.sh -r ~/male_3dDNA/assembly.rawchrom.assembly ~/assembly_male/bwa_index/assembly.fasta ~/aligned/merged_nodup.txt` and I'm getting the same series of errors. 

Interestingly, the FINAL.fasta file is being made, but there is not a difference in the number of chromosomes.

![image](https://user-images.githubusercontent.com/56414662/116789315-437f1280-aa7c-11eb-8273-70b9d2d003c4.png)

This being said, the Hi-C data is definitely making chromosome level scaffolds. This is rawchrom.assemby.hic file. We're expecting 30 chromosomes and the squares add up.

![image](https://user-images.githubusercontent.com/56414662/116789418-affa1180-aa7c-11eb-9b2c-76b5d48fe760.png)

Is there a way to check if the temporary files were made correclty (temp.fasta, temp.cprops, temp.assembly)? If not all I can think of is trying to run the 
`bash ${pipeline}/finalize/construct-fasta-from-asm.sh temp.cprops temp.asm temp.fasta | awk -f ${pipeline}/utils/wrap-fasta-sequence.awk - > ${label}.FINAL.fasta` line individually.

Thanks again for all of your help!
Dustin

**Comment by dudcha** [comment]
Hey Dustin,

Can you send me your fasta and the final.assembly file? olga.dudchenko hosted on bcm.edu.

Olga
