### ISSUE TITLE
reverse-single-fasta.awk or reverse-fasta.awk?

### ISSUE THREAD

**Issue by tiramisutes** [aidenlab/3d-dna#12]
Dear,
I run the 3D DNA pipeline for my genome and find follows problem:
```
awk: fatal: can't open source file `/public/home/software/3d-dna/utils/reverse-single-fasta.awk' for reading (No such file or directory)
```
I check the 3D DNA on GitHub and only find the reverse-fasta.awk script. So, are they the same?

**Comment by dudcha** [comment]
Hi tiramisutes,

Please note that the diploid version of the pipeline is currently under active development. If you would like to run the diploid version of 3d-dna I would suggest running the original commit for 3d-dna from March 2017: https://www.dropbox.com/s/yq5oeuh0c9dlzhw/manual_180322.pdf?dl=0. We hope to update the merge block of 3D-DNA within the next few weeks.

Best,
Olga

**Comment by dudcha** [comment]
Hi tiramisutes,

This i to let you know that there is a preliminary update to merge here: https://github.com/theaidenlab/AGWG-merge if you want to give it a try. I expect we will merge it with the main branch soon.

Olga

**Comment by dudcha** [comment]
This is now merged.

**Comment by tiramisutes** [comment]
Thanks, I will check and have a try.
