### ISSUE TITLE
can't open .hic file in juicerbox. error loading .hic file

### ISSUE THREAD

**Issue by kuangzhuoran** [aidenlab/3d-dna#121]
The size of file .hic(0.hic/1.hic/2.hic) is only 380kb. here are my logs, and I notice two lines in .err file. I don't know what the problem is.   Maybe I can try to re-run.

![64c192db7c8841e77af2dc1694c8de3](https://user-images.githubusercontent.com/76553133/121152380-b8ade680-c877-11eb-9f1a-105072b06773.png)

And  I checked the result of the juicer and found no abnormalities.

my process is like : juicer   -    3d-dna    -    ......

[3ddna.sh.err.txt](https://github.com/aidenlab/3d-dna/files/6614898/3ddna.sh.err.txt)
[3ddna.sh.out.txt](https://github.com/aidenlab/3d-dna/files/6614899/3ddna.sh.out.txt)

Thanks !
 kzr

**Comment by kuangzhuoran** [comment]
version 180922 ,  Linux

**Comment by dudcha** [comment]
Hi krz,

There seem to be some slurm-specific errors, among them at least an out-of-memory error when building hic file. Try allocating more memory to the job.

Best,
Olga
