### ISSUE TITLE
Scaffolding without Hi-C data

### ISSUE THREAD

**Issue by khush876** [aidenlab/3d-dna#122]
Hi, 

I have pretty good assembly of a plant genome using HIFI reads from PacBio. I do not have Hi-C data for scaffolding.  Is there a way to scaffold the assembly? 

Any suggestion/advice is much appreciated !!!

Thank you

**Comment by dudcha** [comment]
Hello,

Please address general inquiries to aidenlab.org/forum.html.

Overall there are many ways to scaffold genomes with data other than Hi-C. We however do not provide support for those data types and tools.

Thanks,
Olga

**Comment by khush876** [comment]
Thank you for your reply. I appreciate that.
