### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by Kai-Maker1** [aidenlab/3d-dna#123]
Hi，3D-dna community，
         This is my first time to use your software，my next step is to use juicerbox，but there are so many files that I couln't find the needed .hic and . assembly. Can you help me ?
          
![微信图片_20210716103528](https://user-images.githubusercontent.com/61792719/125883153-6a232c3e-d65c-45fe-96cc-c1c25cba90df.png)

**Comment by dudcha** [comment]
Please consult the Genome Assembly Cookbook hosted on dnazoo.org/methods. 

Best, -Olga
