### ISSUE TITLE
3d-dna on a very large genome

### ISSUE THREAD

**Issue by agolicz** [aidenlab/3d-dna#124]
Hi,
We have pacbio hifi reads for a very large plant genome (haploid genome size 13Gb, 6 chromosomes, largest chromosome ~4 Gb). Reads will be assembled using hifiasm. We are thinking of using Hi-C data for scaffolding (no data generated as of yet), but from experience I know that with genomes/chromosomes that large we tend to run into various memory and size limits (max allowed chromosome length etc). I am trying to gauge whether using 3d-dna on such genome would even be possible. If yes what would be the expected memory usage.? Are there any obvious issues we would run into? I would very much appreciate any guidance on this as it would guide our project design choices.

All the best,
Agnieszka

**Comment by dudcha** [comment]
Hi Agnieszka,

We’ve used 3d-dna/jbat to assemble an axolotl. There may be some tweaks necessary like dropping the lowest resolutions in contact maps for speed if they are not necessary, but it is possible, to be sure.

Olga

**Comment by agolicz** [comment]
Hi Olga,
Many thanks! Hi-C data it is. May I ask if you managed to achieve chromosome level assemblies? Is there perhaps an associated manuscript?
Best,
Agnieszka

**Comment by dudcha** [comment]
Hi Agnieszka,

The same was we do all our assemblies. You can find many examples here https://www.dnazoo.org/, including the Genome Assembly Cookbook (hosted on the methods page) with some recommendations.

Best,
Olga

**Comment by agolicz** [comment]
Thanks! I am closing for now. I might be back when the data arrives :)

Agnieszka
