### ISSUE TITLE
Ask the assembly time of HIC mounted genome

### ISSUE THREAD

**Issue by ld9866** [aidenlab/3d-dna#125]
Hello, I am using 3D DNA software to mount HIC data with default parameters, but this step has taken me a lot of time. It has been about five days now. How long does it take for a 1.7g genome?At the same time, I also want to use software to assemble a mammalian genome of about 2.5G. How long will it take？

**Comment by dudcha** [comment]
Hello,

I am not sure what "mount" refers to here. Assembling a genome primarily depends on 1) how fragmented the orignal draft is and 2) how much Hi-C data are you using. With ~30X data a typical runtime for a mammalian-size genome is 1-3 days depending on the level of fragmenting (and .0.hic one usually gets within 1-5h).

Olga

**Comment by ld9866** [comment]
OK!
Thank you very much for your reply. I will try your suggestion.
