### ISSUE TITLE
Assembly file contains multiple entries of the same contig. Exiting!

### ISSUE THREAD

**Issue by Zhaoxi-Liu** [aidenlab/3d-dna#126]
Hi,

When I run <run-asm-pipeline.sh> using this  command "run-asm-pipeline.sh -r 5 -m diploid --editor-coarse-norm "NONE" ../references/mel_contigs_pilon.fasta ../aligned/merged_nodups.txt  "
 I got this errer  "  :( Assembly file contains multiple entries of the same contig. Exiting! "
and also 
" tail: +: invalid number of bytes
tail: +: invalid number of bytes
tail: +: invalid number of bytes
…… "

the vesion is 3d-dna/190716

Although it seems that I got all the files including rawchrom.hic and final .assembly and so on, when I use JBAT to open them, there are not large scaffolds but small fragments.  The scaffolds are even smaller than the contigs before the assembly. Could you tell me what the problems are? 
![JBAT](https://user-images.githubusercontent.com/56250130/127619235-45fee212-cac5-483f-bd4b-a0b7c819df8f.png)

thanks a lot !!!

**Comment by dudcha** [comment]
Hi,

I believe I have answered this on the forum. Hope it is of some help.

Best,
Olga
