### ISSUE TITLE
Is there a faster way

### ISSUE THREAD

**Issue by ld9866** [aidenlab/3d-dna#127]
Hello!
when l use run-asm-pipeline.sh to get the final things,l find the speed is really slow. is there any way to use multicore to get the result quicker?
Yours!

**Comment by dudcha** [comment]
The pipeline is already parallelized if you have GNU parallel. If you do not have parallel it will give you a warning. Otherwise you should see the multiple cores being utilized during scaffolding. If there is a particular step that is you concern please list details.

Olga
