### ISSUE TITLE
Resuming after stopping a run

### ISSUE THREAD

**Issue by cgy0627** [aidenlab/3d-dna#129]
Hello,

I was wondering if there's a way to resume a run after pausing it. I know in some other tools like IQ-TREE running the same command line in the same directory after pausing a run resumes from where it left off last. Does 3d-dna have a similar method to resume a run?

Thanks in advance.

Jenny

**Comment by dudcha** [comment]
Hi Jenny,

There is some workflow control using the --stage option:

-s|--stage stage					Fast forward to later assembly steps, can be polish, split, seal, merge and finalize.

Best,
Olga
