### ISSUE TITLE
3d-dna java how to change this error

### ISSUE THREAD

**Issue by wangchengww** [aidenlab/3d-dna#130]
![image](https://user-images.githubusercontent.com/50773859/132435082-ed78d5d7-e6e9-4455-a7be-c3f306c8bfc3.png)
![image](https://user-images.githubusercontent.com/50773859/132435262-339af1ef-b2fb-4a88-925d-ac5ec9c96e59.png)

**Comment by dudcha** [comment]
Hi,

Juicebox cannot build the assembly map because it is running out of memory. How much memory are you allocating to the run? Is this a particularly large genome or something?

Olga

**Comment by wangchengww** [comment]
Hello, I use the default setting. Here are my file size and Server memory usage.I have running two times and get the same error! but my another data&nbsp; running successfully!










王成
服务专员
澳华集团


 联系我












&nbsp;Please Help!!!Thanks!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aidenlab/3d-dna"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 中午11:03
***@***.***&gt;;
抄送:&nbsp;"Wang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [aidenlab/3d-dna] 3d-dna java how to change this error (#130)





 Hi,
 
 Juicebox cannot build the assembly map because it is running out of memory. How much memory are you allocating to the run? Is this a particularly large genome or something?
 
 Olga
 
 &gt; On Sep 7, 2021, at 9:14 PM, wangchengww ***@***.***&gt; wrote:
 &gt; 
 &gt; ﻿
 &gt; 
 &gt; 
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangchengww** [comment]
> Hi, Juicebox cannot build the assembly map because it is running out of memory. How much memory are you allocating to the run? Is this a particularly large genome or something? Olga
> […](#)
> On Sep 7, 2021, at 9:14 PM, wangchengww ***@***.***> wrote: ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hello, I use the default setting. Here are my file size and Server memory usage.I have running two times and get the same error! but my another data&nbsp; running successfully!
![image](https://user-images.githubusercontent.com/50773859/132442002-ac413dc1-f928-4ded-ad44-6772fd006590.png)
![image](https://user-images.githubusercontent.com/50773859/132442019-34ba5046-0d4f-4f2c-a690-71b19ef8d8b5.png)
![image](https://user-images.githubusercontent.com/50773859/132442028-1fbbcdff-4226-4c57-85ac-2c27926f2aab.png)

**Comment by dudcha** [comment]
I don’t think this is about Juicebox given you get thrown out at 25G. Pethaps your other dataset fits. If you need to tweak memory requirements for he Java job you can adjust 

 https://github.com/aidenlab/3d-dna/blob/master/visualize/juicebox_tools.sh

Olga

**Comment by wangchengww** [comment]
> I don’t think this is about Juicebox given you get thrown out at 25G. Pethaps your other dataset fits. If you need to tweak memory requirements for he Java job you can adjust https://github.com/aidenlab/3d-dna/blob/master/visualize/juicebox_tools.sh Olga
> […](#)
> On Sep 7, 2021, at 10:30 PM, wangchengww ***@***.***> wrote: ﻿ Hi, Juicebox cannot build the assembly map because it is running out of memory. How much memory are you allocating to the run? Is this a particularly large genome or something? Olga … On Sep 7, 2021, at 9:14 PM, wangchengww @.***> wrote: ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hello, I use the default setting. Here are my file size and Server memory usage.I have running two times and get the same error! but my another data running successfully! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

OK， Thanks@ I'll try!! and look at what the result might be!

**Comment by wangchengww** [comment]
> > I don’t think this is about Juicebox given you get thrown out at 25G. Pethaps your other dataset fits. If you need to tweak memory requirements for he Java job you can adjust https://github.com/aidenlab/3d-dna/blob/master/visualize/juicebox_tools.sh Olga
> > […](#)
> > On Sep 7, 2021, at 10:30 PM, wangchengww _**@**_._**> wrote: ﻿ Hi, Juicebox cannot build the assembly map because it is running out of memory. How much memory are you allocating to the run? Is this a particularly large genome or something? Olga … On Sep 7, 2021, at 9:14 PM, wangchengww @.**_> wrote: ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hello, I use the default setting. Here are my file size and Server memory usage.I have running two times and get the same error! but my another data running successfully! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> OK， Thanks@ I'll try!! and look at what the result might be!

Thanks @dudcha ,I adjust the juicebox_tools's java parameter, now it works !
