### ISSUE TITLE
edit-mnd-according-to-new-cprops.sh failed in non-parallel mode

### ISSUE THREAD

**Issue by cgjosephlee** [aidenlab/3d-dna#14]
`edit-mnd-according-to-new-cprops.sh` failed when GNU parallel was not installed.

line 21
`[ $parallel == "true" ] && parallel -a ${mnd} --pipepart --will-cite --jobs 80% --block 1G "awk -f ${edit_mnd_script} ${new_cprops} - " || awk -f ${edit_mnd_script} ${new_cprops} -`

should be
`[ $parallel == "true" ] && parallel -a ${mnd} --pipepart --will-cite --jobs 80% --block 1G "awk -f ${edit_mnd_script} ${new_cprops} - " || awk -f ${edit_mnd_script} ${new_cprops} ${mnd}`

**Comment by dudcha** [comment]
Joseph,

Thank you, will fix in the next update.

Best,
Olga

**Comment by dudcha** [comment]
Joseph,
Thank you, this is now fixed.
Olga
