### ISSUE TITLE
Questions for getting the detail imformation between original scaffolds and the final assembly

### ISSUE THREAD

**Issue by caixu0518** [aidenlab/3d-dna#17]
Recently, I used 3D-DNA and JuicerBox to anchor scaffolds to chromosomes, and got satisfactory results. However, I encountered a problem with coordinate updating and I hope to get your help.

I already have gene coordinates on scaffolds, and I wanted to update gene coordinates from scaffolds to chromosomes. but I don't know how to extracted the original detail scaffolds information from the final *.hic file and *.assembly file.  I realy hope you can give me some advice. 

Kind regards,

Xu Cai

**Comment by dudcha** [comment]
Hi Xu Cai,

This is not an issue with 3D-DNA. I have provided some suggestions on the forum, happy to continue the discussion there.

With best wishes,
Olga
