### ISSUE TITLE
Valid Hic data

### ISSUE THREAD

**Issue by wenjiexiaomeng** [aidenlab/3d-dna#19]
Hi, 
I have read the paper and your team created a magic pipeline for  the chromosome level genome assembly! 
Now I have a 3.7Gb genome and I want to use this pipline to get a chromosome level genome, but I don't know how much valid Hic data should I prepare for this.. so I wiil appreciate it if you give me some advice about this.

Best,
Wenjie

**Comment by dudcha** [comment]
Hi Wenjie,

Thanks for the kind words! Since this is not a pipeline issue question, could you please post this on our forum aidenlab.org/forum.html?

I will do my best to share our experience on the issue.

Best,
Olga

**Comment by wenjiexiaomeng** [comment]
Thanks for your reply Olga, I am sorry that I create a not related question here, I will post it on the forum.

Best,
Wenjie
