### ISSUE TITLE
Appropriate parameters for scaffolding

### ISSUE THREAD

**Issue by ghuryejay** [aidenlab/3d-dna#20]
Hi,

We have a genome of size ~3Gbp and have about 30x Hi-C data. The input assembly N50 is 4.8 Mbp and had 4738 contigs. We ran 3d-dna as follows:

`bash run-asm-pipeline.sh -m haploid -i 15000 -r 2  assembly.fasta merged_nodups.txt`

The corrected input assembly had N50 of 3.2 Mbp and 7219 contigs. Also, the resulting scaffolds had a large number of short inversions. We observed the similar issue while setting the `-r` parameter from 1 to 10.  Do you recommend any specific parameters to run 3d-dna in this case? We get decent scaffolds if we turn the input assembly correction off (setting `-r 0`), but it contains large errors present in the input assembly. Any help with this is appreciated. 

Thanks!

**Comment by sa501428** [comment]
Hi! 
Can you please post this to our forum? aidenlab.org/forum.html
We use github for tracking bugs.
Thanks!

**Comment by ghuryejay** [comment]
Thanks, will post there.

**Comment by ghuryejay** [comment]
The link you provided directs me to a blank page.

**Comment by sa501428** [comment]
Are you sure? Is google groups blocked by your firewall? It should show: 
<img width="1224" alt="screen shot 2018-09-06 at 11 28 19 pm" src="https://user-images.githubusercontent.com/6503789/45198562-c0ef1800-b22c-11e8-9faa-5e3f57663cbe.png">

**Comment by ghuryejay** [comment]
Got it, thanks.
