### ISSUE TITLE
Broken Pipeline in 'finalize' step

### ISSUE THREAD

**Issue by Hsu-Che-Wei** [aidenlab/3d-dna#29]
Hi, 
thank you for your useful pipeline, yet I run into this issue as titled. 

The output in finalize step is as followed:

**/home/hpc/crlee/HiC/3d-dna-master/run-asm-pipeline.sh -s finalize ./references/goya2.contigs.fasta ./HIC/aligned/merged_nodups.txt
version: 180922
 -s|--stage flag was triggered, fast-forwarding to "finalize" pipeline section.
###############
Finilizing output:
... -s flag was triggered, treating all contigs/scaffolds shorter than 15000 as unattempted.
... -l flag was triggered. Output will appear with headers of the form goya2.contigs_hic_scaffold_#.
... -g flag was triggered, making gap size between scaffolded draft sequences to be equal to 500.
Analyzing the merged assembly
...trimming N overhangs
...adding gaps
tail: error writing 'standard output': Broken pipe
tail: error writing 'standard output': Broken pipe
tail: error writing 'standard output': Broken pipe**

I have confirmed many times that I met all the dependencies required, and there is no problems in other steps except "finalize".

BASH = 4.1.2
GNU Awk = 4.2.1
GNU coreutils sort = 8.25
GNU parallel = 20160622

Do you know what cause this problem?

Thank you very much!

**Comment by dudcha** [comment]
Hi,

This seems to be an error coming form the fasta indexing step.

comment out the last line in the 3d-dna/finalize/construct-fasta-from-asm.sh to keep the tmp.index.txt file and see what it looks like. Perhaps this will give some idea what may be the issue.

(A typical source of error here are older bash versions that cannot handle associative arrays, but yours seem to be high enough. Let’s see if the file looks reasonable or perhaps something wrong happening upstream.)

Best,
Olga

**Comment by Hsu-Che-Wei** [comment]
Here is the tmp.index.txt:
[tmp.index.txt](https://github.com/theaidenlab/3d-dna/files/2569139/tmp.index.txt)

Is there any problem?

**Comment by dudcha** [comment]
No, looks fine to me. 

comment out line 142 in 3d-dna <https://github.com/theaidenlab/3d-dna>/finalize <https://github.com/theaidenlab/3d-dna/tree/master/finalize>/finalize-output.sh

and try to run directly 

Try to run directly 

tail -c +23 temp.fasta
(first)
tail -c +306712145 temp.fasta
(last)

If nothing suggestive comes up perhaps you can share the files and I can try to reproduce to investigate.

Olga

**Comment by Hsu-Che-Wei** [comment]
When I run
 tail -c +23 temp.fasta
(first)
tail -c +306712145 temp.fasta
(last)

it just output the sequences in fasta format like this:

**tail -c +23 temp.fasta
CTTTCATTCTATAATTGACCAATTTTTTTTTTCCTTCCTTTATCTTGGGGGTTTCAGAAGTGTGATTGATGGGGTGGGGG
TAGCTTTCTTTCAAAGTTCATACGTGTTGCATCTTTGGTAGTAGAAGAAATTGAACCTATATTATAAAATAAATGTGCAT
CTTATGTCCATATCTCAATTTGATAGAATAATCTTCTTTGTGTGACGATTGAAGTTGAAGTCTTTTAATTCTTTGTTGAT
TTAAGTCATTTATCTTCGATAATTTTTTTGTTAAGAAAAAGAGGTTATATATGCAAATAATGTTATGTTTTTCATTTTTC
GCTTTAGTTTTCCTATTGAATATTGAAAAGTAATAAGGATTAGACTTGTGGTCGAAACTTCCTCTACAATATCGTCATCC
AAGTAGAATTTAACCAACAACACTTTTGGATGAATTGGTTTGGTTCCCCTACATATGCATAGTGCACACAGAAGAATATT
GAATTCAAATGTTATTATTTCTGACATGCAAGCTATTGAAGAGGTCATCTAGATGAAGACTTTATATACTCAATATACTT
CTCAAGTTTATGTTCTTCAACTTCAACAACGGAATATTTAGCTATTGGAAAATCGCCATTGATTAGCACAGTCTCCATTA
TTGGCGTAGCTCTGCCTTATGGGGACAGCGGAAAAGAAGAAATAGTTGGAAGAAAGGAAGAAAGAATTGAAAAATTTTTA
GGTTGATAACCAAGTCCAATAGCAGACTTGGAATCTAATGTACTTATAGTTATACTTGGCCTACCAATCTTTTAATTTAA
ACTTGAATTTTTATTATAATGGAAAATTTTAAAATATTATGGACAAACCTAAAACTAAGCATATAGATTAGAGACAAAAT
TGAAATCAAATAAATGATGCTAATGTGTTTTTTTTACCCTCAAATTTTTAACTTTTCTCAAGTATTTTTACAGAGATCCT
TAATCGAGGGTCAAATTTGAACTTTCAACGAGGTTAGAACAACCTTGTATGTTTAAAATATTTTCCTATAATTTAGCATG**
...
...
...
**tail -c +306712145 temp.fasta
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN**

Shall I send you the draft assembly and the merged_nodups.txt or other intermediate files?
Thank you for your rapid response!

**Comment by dudcha** [comment]
Hsu,

Run these commands exactly like you would have via 3d-dna. If you are running on a cluster submit as a job etc. Because you seem to be able to run this without error.

Olga

**Comment by Hsu-Che-Wei** [comment]
Olga,

Sorry, I don't get exactly what you mean.
I run 3d-dna pipeline on a PBS cluster, so I submit the job through "qsub".
So are you suggesting that I run it directly instead of submitting through "qsub"?

Che-Wei

**Comment by Hsu-Che-Wei** [comment]
But even if I run it directly, it still stop at ...adding gaps

**Comment by dudcha** [comment]
Ok. This covers the issue of cluster dependencies, I suppose. Can you share the files? Write to olga.dudchenko@bcm.edu <mailto:olga.dudchenko@bcm.edu>.

Best,
Olga

**Comment by Hsu-Che-Wei** [comment]
Sure, I will send you tomorrow

**Comment by dudcha** [comment]
Do you mind trying/checking if any of the things/suggestions here are relevant to you?

https://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error

Perhaps trying dd insertion into lines 62 and 64 of 3d-dna/finalize/construct-fasta-from-asm.sh would address this? I am happy to continue with the files, but if system specific.

Thanks,
Olga

**Comment by Hsu-Che-Wei** [comment]
Olga, 
Thank you for your suggestion, I will definitely try it. But I have no access to my cluster now. I will tell you if it works or send you the files if it doesn’t.

Best, 
Che-Wei

**Comment by Hsu-Che-Wei** [comment]
Olga,
The pipeline error is solved by trying dd insertion into lines 62 and 64 of 3d-dna/finalize/construct-fasta-from-asm.sh, yet the final fasta (.FINAL.fasta) is not a chromosome level assembly, in fact, it becomes more fragmented than draft genome. Here is the log file: 
[job_3d.txt](https://github.com/theaidenlab/3d-dna/files/2598314/job_3d.txt)
It seems to me that the pipeline did not complete its run. Do you know anything could be responsible for this?

**Comment by dudcha** [comment]
Consider looking through related threads on aidenlab.org/forum.html on how to interpret input including misjoin correction tuning. See also notes in the genome assembly cookbook on the most common scenarios that require tuning.

Best,
Olga

**Comment by Hsu-Che-Wei** [comment]
Olga,
Thank you for your suggestions, I found from some thread that I should play with editor parameters in order to saturate track "depletion_score_wide_at_step_0". I achieved that by using parameters " --editor-coarse-resolution 2500000  --editor-coarse-region 12500000 --editor-fine-resolution 100000 --editor-saturation-centile 60 --editor-repeat-coverage 20", however, the results are still unsatisfactory. Here are the hic graph from juicebox : 

![default_param](https://user-images.githubusercontent.com/44936028/48826857-7baba280-eda6-11e8-91fb-5dba10839c22.PNG)
![editor_param](https://user-images.githubusercontent.com/44936028/48826864-8403dd80-eda6-11e8-8e7f-489070daea04.PNG)
![rawchrom_with_editor_param](https://user-images.githubusercontent.com/44936028/48826873-8a925500-eda6-11e8-8cc2-220050b646ff.PNG)

I guess the useful hic data is just not enough to achieve chromosome-level assembly, but maybe you see it differently? Do you have other suggestions to improve it? Thanks!

Best,
Che-Wei

**Comment by Hsu-Che-Wei** [comment]
The top graph is the default parameters, the middle is with editor parameters, and the bottom is the rawchrom with editor parameters.

**Comment by dudcha** [comment]
Hsu,

Please move this discussion to the forum, this is not a code bug issue.

Note that your parameter tuning resulted is no misjoin correction: the bed track is empty. Is this what you wanted?

Your data is noisy but you can see chromosomes in the graphs you share. Does not look the best dataset but seems you can get reasonably far with this.

Olga

**Comment by GitHub-Lujianjun** [comment]
> The pipeline error is solved by trying dd insertion into lines 62 and 64 of 3d-dna/finalize/construct-fasta-from-asm.sh,

what's means try`insertion 

> Olga,
> The pipeline error is solved by trying dd insertion into lines 62 and 64 of 3d-dna/finalize/construct-fasta-from-asm.sh, yet the final fasta (.FINAL.fasta) is not a chromosome level assembly, in fact, it becomes more fragmented than draft genome. Here is the log file:
> [job_3d.txt](https://github.com/theaidenlab/3d-dna/files/2598314/job_3d.txt)
> It seems to me that the pipeline did not complete its run. Do you know anything could be responsible for this?

what's means  trying dd insertion into lines 62 and 64 of 3d-dna/finalize/construct-fasta-from-asm.sh; add  "dd" at the beginning of the line or end of the line? but what's means here "dd" for the bash script? or you mean to deleate these two lines?
![image](https://user-images.githubusercontent.com/32757740/56845924-0f0b7580-68fb-11e9-8c82-3609cc81f9d4.png)
