### ISSUE TITLE
How to deal with fragments that are not anchored on the chromosome, after I ran run-asm-pipeline-post-review.sh.

### ISSUE THREAD

**Issue by Xuelei-Dai** [aidenlab/3d-dna#30]
Hello,
After I ran `run-asm-pipeline-post-review.sh`,I found that there are still many fragments(about 10%) that are not anchored on the chromosome.Can you give me some suggestions for improvement, or artificially anchor it on the chromosome?

Thanks!

**Comment by dudcha** [comment]
Hello,

Well, if you have not anchored them in review, they will not be anchored to chromosomes after. I am not sure I understand what you are trying to do.

Generally speaking there are two sources of unanchored sequence: sequences in the draft smaller than the input size (default is 15kb) and sequences flagged as debris. Depending which case it is in your case, you may choose to run 3d-dna with smaller input size (at the expense of somewhat lower lower accuracy) or look into misjoin detection.

Olga

**Comment by Xuelei-Dai** [comment]
Thank you very much for your quick reply！
I have an idea: because 3d-dna needs to interrupt and correct contig, it also depends on the quality of HiC data. So, I want to last the interrupted sequence to contig (many broken sequences are dropped from contig), and then anchor the interrupted sequence to the chromosome based on the contig information without interruption.

**Comment by dudcha** [comment]
I do not understand what you mean. Perhaps you are describing sealing which is performed by the pipeline, but I am not sure. Note that if those sequences are indeed due to misassemblies, you should not be reincorporating them.

**Comment by dudcha** [comment]
Also, since this is not really a bug or code issue, I suggest that this discussion is moved to aidenlab.org/forum.html <http://aidenlab.org/forum.html> where we try to give user support. There may be some discussions threads already there that may be relevant to your case.

Best,
Olga

**Comment by Xuelei-Dai** [comment]
Ok,thanks for your suggestion.
