### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Xuelei-Dai** [aidenlab/3d-dna#33]
Hello,
I want to know the resolution of 3d-dna, I can't find it.

**Comment by dudcha** [comment]
Fantasticair,

I don’t know what you mean by resolution.

Olga

P.S.: please use forum for general inquiries. We appreciate your understanding.

**Comment by Xuelei-Dai** [comment]
Thanks for your reply!
In other words, how much bp or kb is used as a window size when the result of 3d-dna is displayed in the juicebox?

**Comment by dudcha** [comment]
Fantasticair,

I did my best to answer this on the forum.

Best,
Olga
