### ISSUE TITLE
How to visualize chromosomes in a given order in a juicebox

### ISSUE THREAD

**Issue by Xuelei-Dai** [aidenlab/3d-dna#34]
Hello,
After running run-asm-pipeline.sh with 3d-dna software, I manually adjusted the cluster map of the chromosome distribution with the juicebox locally, but I want to arrange the cluster heat map of the chromosome according to the given chromosome number. How should I adjust?
Best,
fantasticair

**Comment by dudcha** [comment]
Fantasticair,

Please post on forum and give a bit more information about what you are trying to achieve. I do not understand the question, I am sorry.

Closing this and previous as not issues.

Olga

**Comment by dudcha** [comment]
Is it that you are trying to move the chromosomes around? You can do that in Juicebox Assembly Tools. I assuming that's what you mean when you say you adjusted the cluster map locally? There really is no difference, you'd presumably do it exactly the same way, by just moving a group of contigs together..
