### ISSUE TITLE
temp.scaffolds_FINAL.asm_mnd.txt does not exist or does not contain any reads

### ISSUE THREAD

**Issue by mictadlo** [aidenlab/3d-dna#35]
Hi,
I tried to run juicebox_scripts pipeline but I ran into this problem https://github.com/phasegenomics/juicebox_scripts/issues/10 . At the /3d-dna/visualize/run-assembly-visualizer.sh step I got this error:
```
:) -p flag was triggered. Running with GNU Parallel support parameter set to false.
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.scaffolds_FINAL.asm_mnd.txt does not exist or does not contain any reads.
``` 

By any chance, do you know what I missed?

Thank you in advance,

Michal

**Comment by dudcha** [comment]
Michal,

Looking at the feed on Phase Genomics github it seems there were all the correct suggestions. Have you addressed the name mismatch issue?

Best,
Olga

**Comment by mictadlo** [comment]
Hi Olga,
Thank you.  Yes, it works. 

Best wishes,

Michal
