### ISSUE TITLE
run-asm-pipeline.sh with java error 

### ISSUE THREAD

**Issue by wingwingWY** [aidenlab/3d-dna#36]
Hi , I ran 3d-dna for a plant genome  with the command:
`sh 3d-dna/run-asm-pipeline.sh --mode haploid --input 10000 ./curated.fasta ./merged_nodups.txt`

I got error infomation as follows:
```
Writing body
...detecting misjoins in round 0 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
HiC file version: 8
ERROR [2019-01-16 00:14:58,882]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
        at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
        at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
        at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
        at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
        at juicebox.tools.HiCTools.main(HiCTools.java:85)
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
HiC file version: 8
ERROR [2019-01-16 00:15:02,847]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
        at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
        at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
        at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
        at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
        at juicebox.tools.HiCTools.main(HiCTools.java:85)
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.1.*
...applying edits to cprops file

```
Do you know what cause this problem?

Thank you very much!

**Comment by dudcha** [comment]
Hi Wingwing,

Sorry for the delay in answering due to travel. This is the first time I see an error like this. To help with tracing it, can you please let me know if any of the .hic files have been written (size >0, you can open them in Juicebox/Juicebox Assembly Tools). I suspect that they have not been written: I do not see the expected output after "Writing body". What does the error stream look like? What are your system specs?

Best,
Olga

**Comment by dudcha** [comment]
It seems clear from this that your .hic file was not created. Check the inputs: .0.assembly file and the original mnd file. It seems that your parallel may have some issues so that the mnd file does not get generated perhaps.

Try running the visualization script only:

{3d-dna}/visualize/run-assembly-visualizer.sh <0.assembly> <original.mnd.txt>

This will run without a cleanup flag and leave you with a tmp file to examine. Let’s see if it is empty. If it is something’s wrong with parallel. You’d want to examine the version or run without parallelization (latter though I would not advise).

Best,
Olga

**Comment by ViriatoII** [comment]
Hi,

I'll come here with a question:

Where should those files (0.assembly and original.mnd.txt) be?

Is that **original.mnd.txt** something different of the **merged_nodups.txt** that Juicer automatically creates ?

Cheers,
Ricardo

**Comment by dudcha** [comment]
Ricardo,

Look for files that are *.0.assembly and *.mnd.txt, where * is the name of the fasta file you pass without the fasta/fna/fa at the end. The mnd for the suggested step is the same as the original mnd created by juicer: you’ll see it linked.

Best,
Olga

**Comment by wingwingWY** [comment]
Hi, Olga
I will rerun 3d-dna without parallelization  to check the  parallel problem. 
Thank you for your help.

**Comment by ViriatoII** [comment]
So I ran /run-assembly-visualizer.sh like you suggested and the temporary file was not created:

>...Remapping contact data from the original contig set to assembly
visualize/run-assembly-visualizer.sh: line 161: temp.HiCi_pseudochromosomes.0.asm_mnd.txt: No space left on device
...Building track files
...Building the hic file
temp.HiCi_pseudochromosomes.0.asm_mnd.txt does not exist or does not contain any reads.

I wanted to run 3d-DNA without parallelization but I don't know how to do it. 

However, and very interestingly,  3d-dna now runs normally, exactly with the same commands. Somehow the problem with parallel solved itself when running the visualizer??

**Comment by dudcha** [comment]
Viriatoll,

It says no space left in device. Seems rather suggestive.

Olga

**Comment by ViriatoII** [comment]
Dear Olga,

Sorry, you're right, the disk was full, problem solved. But here is the real error when running visualize (same as when running run-asm-pipeline.sh) 

>...Remapping contact data from the original contig set to assembly
Error in tempfile() using template /scratch/parXXXXX.par: Parent directory (/scratch/) does not exist at /usr/bin/parallel line 3993.
...Building track files
...Building the hic file
temp.HiCi_pseudochromosomes.0.asm_mnd.txt does not exist or does not contain any reads.

This is probably related to me working on a cluster without sudo permissions?

**Comment by dudcha** [comment]
Hi Viriatoll,

Sorry, I think I have missed this message. Have you been able to resolve this? Do you still need help? Seems that you might have some issue with your local $TMP variable or something like that.

Best,
Olga

**Comment by ViriatoII** [comment]
Hey dudcha,
I just fixed my problem. It was exactly what you said. My $TMPDIR was wrongly set to an unexistent folder. Adding this to my .profile  / .bashrc file fixed the issue:
> export TMPDIR="/tmp"

Thanks!

**Comment by dudcha** [comment]
Happy to hear this is resolved.

Good luck,
Olga
