### ISSUE TITLE
run-asm-pipeline.sh error: bash: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'

### ISSUE THREAD

**Issue by shimiao12345** [aidenlab/3d-dna#40]
run commond:

**export PATH=/software/bash-4.0/bin:/coreutils-8.12/bin/:Gnu-Parallel/parallel20170622/bin/:software/gawk-4.1.1/bin:$PATH
/3d-dna-master/test/script/run-asm-pipeline.sh     IGT9201.fa     merged_nodups.txt**

**then I get an error:**
bash: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
bash: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
bash: error importing function definition for `BASH_FUNC_module'
bash: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
bash: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
bash: error importing function definition for `BASH_FUNC_module'
bash: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
bash: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
bash: error importing function definition for `BASH_FUNC_module'
bash: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
bash: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
bash: error importing function definition for `BASH_FUNC_module'
bash: BASH_FUNC_module(): line 0: syntax error near unexpected token `)'
bash: BASH_FUNC_module(): line 0: `BASH_FUNC_module() () {  eval `/usr/bin/modulecmd bash $*`'
bash: error importing function definition for `BASH_FUNC_module'

**My Linux bash -version  is  version 4.1.2, but I installed the 4.0 version and added it to envrionment PATH.** It still get above errors.

Can you give me some help? Thank you very mush.

**Comment by dudcha** [comment]
Hi shimiao12345,

I've never seen this. Are you running 3D-DNA in some sort of module wrapper? If that's the case, this thread seems relevant: https://stackoverflow.com/questions/36023688/syntax-error-near-unexpected-token

Olga

**Comment by shimiao12345** [comment]
Hi dudcha,
      Thanks for your reply. I have solved it. The method is added "**unset -f `env | sed -n 's/^BASH_FUNC_\([a-z]*\)()=.*/\1/p'`**" to the envrionment.


Bests
