### ISSUE TITLE
when I run run-asm-pipeline.sh,I met some mistake

### ISSUE THREAD

**Issue by hzaumsq** [aidenlab/3d-dna#42]
/public/msq/tools/3d-dna/run-asm-pipeline.sh: line 727: `	  awk 'BEGIN{OFS="\t"; print "chr1", "x1", "x2", "chr2", "y1", "y2", "color", "id", "X1", "X2", "Y1", "Y2"}$1~/:::debris/{print $1, 0, $3, $1, 0, $3, "0,0,0", "debris", 0, $3, 0, $3}' ${current_cprops} | awk -f ${pipeline}/lift/lift-input-annotations-to-asm-annotations.awk ${current_cprops} <(awk '{print $2}' ${current_cprops}) - | awk -f ${pipeline}/lift/lift-asm-annotations-to-input-annotations.awk ${orig_cprops} <(awk '{print $2}' ${orig_cprops}) - > h.old.edits.txt'

**Comment by dudcha** [comment]
Hi hzaumsq,

What’s the mistake?

Best,
Olga

**Comment by jebard** [comment]
Hi Olga,
I am also seeing this problem -- here is my command -- the pipeline is failing at the awk command on line 727 -- my draft assembly names are in the format GBC_# where # is the contig number... 

$run-asm-pipeline.sh -r 1 ../draft.fasta merged_nodups.txt
version: 180922
 -r|--rounds flag was triggered, will run 1 round(s) of misjoin correction.
3d-dna/run-asm-pipeline.sh: line 727: syntax error near unexpected token `('
3d-dna/run-asm-pipeline.sh: line 727: `         awk 'BEGIN{OFS="\t"; print "chr1", "x1", "x2", "chr2", "y1", "y2", "color", "id", "X1", "X2", "Y1", "Y2"}$1~/:::debris/{print $1, 0, $3, $1, 0, $3, "0,0,0", "debris", 0, $3, 0, $3}' ${current_cprops} | awk -f ${pipeline}/lift/lift-input-annotations-to-asm-annotations.awk ${current_cprops} <(awk '{print $2}' ${current_cprops}) - | awk -f ${pipeline}/lift/lift-asm-annotations-to-input-annotations.awk ${orig_cprops} <(awk '{print $2}' ${orig_cprops}) - > h.old.edits.txt'

**Comment by jebard** [comment]
To follow up on this -- run trying to run the visualize assembly -- 

3d-dna/visualize/run-assembly-visualizer.sh: line 168: syntax error near unexpected token `('
3d-dna/visualize/run-assembly-visualizer.sh: line 168: `awk 'BEGIN{OFS="\t"; print "chr1", "sx1", "sx2", "chr2", "sy1", "sy2", "color", "Scaffold_ID", "x1", "x2", "y1", "y2"}{print $1, 0, $3, $1, 0, $3, "0,255,0", "+"$1" (+"$2")", 0, $3, 0, $3}' <(awk '$0~/^>/{$1=substr($1,2); print}' ${assembly}) | awk -v scale=${scale} -f ${lift_input_annotations_script} <(awk '$0~/^>/{$1=substr($1,2); print}' ${assembly}) <(awk '$0!~/^>/' ${assembly}) - > ${genomeid}_asm.scaffold_track.txt'

**Comment by jebard** [comment]
It looks like this is a bash/sh problem -- I was able to get the pipeline to continue by changing the permissions on the run-asm-pipeline.sh file to 755  and execute it directly.

Based on ---  https://github.com/theaidenlab/3d-dna/issues/16

chmod 775 3d-dna/run-asm-pipeline.sh 
[jbard@rant:juicer-safe]$ 3d-dna/run-asm-pipeline.sh -r 1 GBC-Wrapped.fasta merged_nodups.txt 

version: 180922
 -r|--rounds flag was triggered, will run 1 round(s) of misjoin correction.
###############
Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: GBC-Wrapped.0.cprops
...Using merged_nodups file: GBC-Wrapped.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1

**Comment by dudcha** [comment]
Hi Jonathan, hzaumsq,

Glad to hear this is resolved! Best,

Olga

**Comment by baishengjun** [comment]
Hi，
Ihave the same problem and I chmod 775 run-asm-pipeline.sh .but it did not work.
how can I solve it ?
thanks in advance
