### ISSUE TITLE
Is there some way to supply 3D-DNA with a precomputed BAM alignment file?

### ISSUE THREAD

**Issue by SchwarzEM** [aidenlab/3d-dna#45]
I have generated a BAM genomic-alignment file of my Hi-C reads using the Arima pipeline for filtering out errors (https://github.com/ArimaGenomics; I ran this as input to SALSA2), and with bowtie2 rather than BWA mem (which is ~4 times slower than bowtie2).

That was a lot of computing time which I'd prefer not to have wasted.

Is there some way to run 3D-DNA with a precomputed BAM alignment, or do I have to let 3D-DNA go through the entire BAM construction process again?

**Comment by dudcha** [comment]
In theory you could write some scripts to feed your alignments to Juicer, circumventing the alignment step there, using the rest of the code to analyze fragments and dedup the reads and present in the merged_nodups pairwise contact format that is the input to 3D-DNA. It would not be very hard but you'd have to write that yourself: as far as I know there is not ready-to-deploy script for this available.

[Juicer](https://github.com/aidenlab/juicer) however is a very efficient pipeline for analyzing Hi-C data, chances are it will take you less time to run Juicer from scratch on your data than to sneak those bams in.
 
Best,
Olga
