### ISSUE TITLE
How could a final .hic file be created?

### ISSUE THREAD

**Issue by zhangrengang** [aidenlab/3d-dna#5]
Hi. After the finalize stage, I have to create the final .hic map by using Juicer, which is time-consuming. Could it be created from the pipeline?

**Comment by suestring7** [comment]
It's in the directory... If you just `ls *.hic`, you could see the .hic file for each iteration.
(Actually, they've mentioned that in their README.md)
> b) .hic files
“polished” – after polishing stage (for diploid mode only)
“resolved” – after editing and scaffolding
[0123…] – correspond to the assembly at individual editing iterations

**Comment by dudcha** [comment]
Hi,
Note that the latest commit will generate a "final.hic" file in addition to the ones listed by daisyme.
Best,
Olga

**Comment by ViriatoII** [comment]
Does it create a final.hic file for diploid mode as well? Because I'm reading into the code and the only *final.hic that exists is here:

> if [ $diploid == "false" ]; then
                ln -sf ${genomeid}.rawchrom.cprops ${genomeid}.final.cprops
		ln -sf ${genomeid}.rawchrom.asm ${genomeid}.final.asm
		ln -sf ${genomeid}.rawchrom.fasta ${genomeid}.final.fasta
                ln -sf ${genomeid}.rawchrom.hic ${genomeid}.final.hic
fi

**Comment by dudcha** [comment]
Hello Viriatoll,

I am assuming that the question is whether final.hic is created in diploid mode. No, it is not created, and this behavior is expected. In diploid mode one needs to remap Hi-C data to the final assembly in current version.

Best,
Olga
