### ISSUE TITLE
run-asm-pipeline-post-review.sh get an unusual .FINAL.fasta file

### ISSUE THREAD

**Issue by SC-Duan** [aidenlab/3d-dna#56]
Hi,
After I adjust the assembly file generating by run-asm-pipeline, I get the review.assembly file. Then I run run-asm-pipeline-post-review.sh to get the .FINAL.fasta as follows,
./run-asm-pipeline-post-review.sh -s finalize --sort-output --
build-gapped-map -r .review.assembly genome.fa ../aligned/merged_nodups.txt
It is right for the .rawchrom.fasta size, about 1Gb, but the FINAL.fasta is just 100Mb, and there were not distinct error in log.
Can you give me some help? Thanks a lot.

**Comment by dudcha** [comment]
Hi dzaccook,

One common reason of issues with this step is a carriage return symbol introduced when JBAT is run on Windows machine (safeguarded agains in later builds but perhaps not the one you are using.) Have you run review on a win machine? If yes consider doing something like described here: 
http://aidenlab.org/forum.html?place=msg%2F3d-genomics%2F-vc7LhlaFok%2Ft3akAalHCAAJ
Another possible reason is old bash version which does not handle associative arrays. If neither of these cases is your case please share the out and err logs and I'll do my best to take a look.

Best,
Olga

**Comment by SC-Duan** [comment]
Hi Olga,

I run JBAT on an iMAC machine , and my bash version is GNU bash version 4.1.2(1)-release (x86_64-redhat-linux-gnu). I test 3 genomes, of which two genomes were assembied with Bionano data, and these two genomes show error above, another one is normal. Is there anything else I should notice with bionano?

I have uploaded the review log file and review.assembly file, thank you!
[log.txt](https://github.com/theaidenlab/3d-dna/files/3508149/log.txt)
[bionano.FINAL.review.assembly.txt](https://github.com/theaidenlab/3d-dna/files/3508194/bionano.FINAL.review.assembly.txt)

Best,
zac

**Comment by dudcha** [comment]
Zac,


I’m afraid you’ve been reviewing the wrong file. Judging by the fact that your review contains gaps you’ve been reviewing the .FINAL.assembly. Did you load it against the map with gaps or not? In either case, because the .FINAL does not have unique ids (all post-HiC gaps are the same sequence). I can try to think what can be done to alleviate, but generally speaking the workflow recommends the review before the final introduction of gaps (rawchrom=final in haploid case)

Olga

**Comment by SC-Duan** [comment]
Hi Olga,
It works, thank you very much!
