### ISSUE TITLE
How to creat  .hic and .assembly files ?

### ISSUE THREAD

**Issue by wlhCNU** [aidenlab/3d-dna#57]
hi,
   I have generated a BAM genomic-alignment file of my Hi-C reads and the ordering and orientation final.fasta file. Now I want to load .hic and .assembly files to correct assembly errors by Juicebox Assembly Tools.  What should I do to creat .hic and .assembly files?
Thanks

**Comment by dudcha** [comment]
Hi wlhCNU,

Please see Genome Assembly Cookbook for a comprehensive guide on how to work with our tools:
https://www.dnazoo.org/methods

Best,
Olga
