### ISSUE TITLE
How to define the number of threads used

### ISSUE THREAD

**Issue by Jinxian52099** [aidenlab/3d-dna#61]
Hi,
I want to know if there is a parameter could define the number of threads used.
Thanks in advance!

**Comment by dudcha** [comment]
Hello Jinxian52099,

There isn’t a global parameter you can pass to the whole pipeline. By default is uses 80% of available if run with parallel (-j 80%).

Thanks,
Olga

**Comment by eorylel** [comment]
Hi Olga,
Can you possibly add an argument which would define the number of threads for the script? Using 80% of cores is OK if I run it on a dedicated server, but running it on a cluster which is used by many users is a different situation. Simply taking 80% of the available cores on the node may reduce job efficiency and will have an impact on the work of all those who try to run jobs on the same node.
Is parallelisation done with GNU parallel? In that case it may be possible to simply pass on the number of dedicated threads with the parallel -j ?
Thanks,
Lel

**Comment by mscharmann** [comment]
Please add this functionality!
