### ISSUE TITLE
 No resolved files are found

### ISSUE THREAD

**Issue by wuxiaopei0509** [aidenlab/3d-dna#62]
My initial assemble is 670 Mb of contig level and I use the 3d-DNA pipeline to Scaffold the contig. However it runs with errors as follows:
temp.final.0.asm_mnd.txt does not exist or does not contain any reads.
:( No resolved files are found. Please rerun the pipeline to include the scaffold segment. Exiting!
anyone know why it happens?Thanks very much!

**Comment by dudcha** [comment]
Hello wuxiopei0509,

This is too little information for me to be able to give you solid guidance. My suggestion would be to check your input: the message probably suggests that there may be a permissions issue with your files or a discrepancy between the fasta you are feeding and the mnd file i.e. not the same sequences are involved.

Best,
Olga

**Comment by wuxiaopei0509** [comment]
Thanks a lot.The problem above has resolved ,but another exists ,did the pipe only permit the merged_nodups file ,I used the align file from HiCUP and 3D-DNA cannot work ,does the align file wrong?
Thank you !

**Comment by dudcha** [comment]
Hello wuxiaopei0509,

At present 3D-DNA requires the alignments in the merged_nodups.txt format as created by the Juicer pipeline. For details on the format see Juicer wiki: https://github.com/aidenlab/juicer/wiki

For information on how to work with 3D-DNA see Genome Assembly Cookbook: www.dnazoo.org/methods.

Best,
Olga

**Comment by wuxiaopei0509** [comment]
Thanks a lot and I get it !

**Comment by wuxiaopei0509** [comment]
Hi,Olga
Another question ,does the Juicerbox assembly tools only accept the .hc file from 3d-dna pipeline ? I use the .hc file and asssembly file from Lechesis , the Juicerbox tools seem doesn't work.
Thank you

**Comment by dudcha** [comment]
I am not sure what Lachesis outputs are, but I don't think it creates .hic and .assembly files. You can certainly build .hic files and .assembly files that will work for any assembly out there, including Lachesis ones. See Genome assembly cookbook for instructions: if the files are build according to instructions, you can visualize the maps and work in Juicebox Assembly Tools. -Olga

**Comment by wuxiaopei0509** [comment]
Hi,Olga
Thank you for your enthusiastic. The output of Lachesis are Lachesis_assembly.fasta and I create inter.hc from Jucier and import Lachesis_assembly.fasta and inter.hc into Juicebox Assembly Tools.However it is too slow to open the Lachesis_assembly.fasta file.Does it due to the style of Lachesis_assembly.fasta is not suitable?

**Comment by dudcha** [comment]
Juicebox Assembly Tools does not work with .fasta files.

**Comment by wuxiaopei0509** [comment]
Hi,Olga
sorry to bother you .
I want to use ./run-asm-visualizer.sh to make Juicebox-compatible contact map based my own Scaffold which is not from the 3d pipeline,  the script needs in input by  cprops and asm files and  pairwise contact data represented by Juicer merged_nodups.txt file.I can I generate cprops and asm files?
Thank you very much

**Comment by dudcha** [comment]
Hello. See Genome assembly cookbook (dnazoo.org/methods), page 5 for instructions. -Olga
