### ISSUE TITLE
The parameters which could be modified

### ISSUE THREAD

**Issue by WTarabidopsis** [aidenlab/3d-dna#64]
Hi,
When I ran 3d-dna, it generated 5 chromosomes in the end. However, former reports indicated this species should have 12 chromosomes. I checked the `.hic` file in Juicer box and found that there must be some misconnection between contigs. I want to try to modify the parameters of 3d-dna, but there are several parameters for each step, it will cost plenty of time if I tried to adjust every parameter. So, I want to know which parameters are critical for the results and I should take into consideration first?
Below is the result which I ran 3d-dna by using default parameters, hope this could help, thanks in advance!
[mecat.pdf](https://github.com/theaidenlab/3d-dna/files/3695986/mecat.pdf)

**Comment by dudcha** [comment]
Hello WTarabidopsis,

I am assuming by critical you mean critical for the step you care about which, if I understand your request correctly, must be chromosome splitting. The parameters associated with this step are outlined in full help (--help):

**splitter**
--splitter-input-size splitter_input_size
			Splitter input size threshold. Scaffolds smaller than polisher_input_size are going to be placed into unresolved (Default: 1000000).
--splitter-coarse-resolution splitter_coarse_resolution
			Splitter coarse matrix resolution, should be one of the following: 2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000, 1000 (Default: 25000).
--splitter-coarse-region splitter_coarse_region
			Splitter  triangular motif region size (Default: 3000000).
--splitter-coarse-stringency splitter_coarse_stringency
			Splitter stringency parameter (Default: 55).
--splitter-saturation-centile splitter_saturation_centile
			Splitter saturation parameter (Default: 5).
--splitter-fine-resolution splitter_fine_resiolution
			Splitter fine matrix resolution, should be one of the following: 2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000, 1000 (Default: 1000).

I would recommend loading the .wig and .bed files associated with the step. See page 23 in Genome assembly cookbook for some idea on how the step works: splitting and editing are done using the same algorithm. Most likely you will need to play around with coarse stringency and saturation centile.

Best,
Olga

**Comment by melop** [comment]
Following up on this thread. I saw that the misjoin editor calls quite a lot of regions as misassembled. In my case, it looks like this is due to under-estimated gap size between contigs within a scaffold or due to collapsed repeats, which again underestimates the distance between joined contigs. 
Which direction should I adjust the editor_coarse_stringency parameter to make it call few misjoins but only the most severe ones?

**Comment by rob123king** [comment]
I have the same issue that I have two very large chromosomes of 130Mbp and 80Mbp which must need splitting. They must be a combination of chromosomes. I'm also looking to what setting to minimise over scaffolding in this instance.

**Comment by dudcha** [comment]
Hello rob123king,
Please consider using the aidenlab.org/forum.html for inquiries about performance tuning as this is not a bug. Thanks!
Olga
