### ISSUE TITLE
No contact shown in scaffolded chromsomes in the *.final.hic file

### ISSUE THREAD

**Issue by melop** [aidenlab/3d-dna#73]
Thank you for development this wonderful tool, it is the first time I am dealing with Hi-C scaffolding. I made the Hi-C library with the easyHiC protocol, with HindIII as the first enzyme and DpnII as the self-circularization enzyme. The data type is different than other Hi-C, so I wrote my own pipeline to filter and de-duplicated the reads, mapped them with BWA mem, and converted them into the merge_dedup format.
The input assembly has an N50 of 1.5Mb, with the longest scaffold being about 5Mb long. I ran 3d-dna with the following command line:
`run-asm-pipeline.sh -m haploid -r 3 -q 1  --editor-coarse-resolution 50000 --editor-fine-resolution 5000  -g 1000 ref.fasta mnf.txt`

After three iterations, the produced ref.final.fasta file contains the expected 19 chromosomes. However when I tried loading ref.final.hic and ref.final.assembly into Juicebox, no contacts are shown for the full length chromosomes, only contacts are shown for the unassigned scaffolds. 

Is there any problem with my installation? I am attaching the hic figure and the log file.

Thank you!
Ray

[log.zip](https://github.com/theaidenlab/3d-dna/files/4049180/log.zip)

[ref.final.hic.pdf](https://github.com/theaidenlab/3d-dna/files/4049174/ref.final.hic.pdf)

**Comment by melop** [comment]
Sorry for the confusion, it was because I accidentally used a wrong input scaffold assembly.

**Comment by dudcha** [comment]
Hi Ray, Glad this was resolved. Best, -Olga
