### ISSUE TITLE
3d-DNA makes my assembly fragmentary?

### ISSUE THREAD

**Issue by timmy304681** [aidenlab/3d-dna#77]
Hi, 
I started with my assembly .fasta (contig number: 260, legnth: 500 mb, N50:  7.3 mb), but after 3d-DNA, I got .FINAL.fasta (contig number:  5,520, legnth: 500 mb, N50:  0.3 mb). And I used the defaul pipeline:

run-asm-pipeline.sh -m diploid -i 15000 -r 2 ./assembly.fasta ./aligned/merged_nodups.txt

I have no idea how I could optimize my result. I am not sure which step I have something wrong.
Please give me some advise, and how could I let my assembly more chromosome-level?

Thank you.

**Comment by dudcha** [comment]
Hello Yang-Tui,

Please consult the Genome Assembly Cookbook, see dnazoo.org/methods. There are also a lot of relevant discussions on the forum (dnazoo.org/forum = aidenlab.org/forum.html)

Thanks,
Olga
