### ISSUE TITLE
Error durg first iteration ?

### ISSUE THREAD

**Issue by BiodivGenomic** [aidenlab/3d-dna#78]
Dear Olga,
I'm trying to scaffold my genome assembly, and I'm running into some errors...
I'm not sure if the errors come from my side (I checked the files and everything looked fine), or from 3d-DNA itself (as the first error would suppose)....
Any help would be very helpful !

$ run-asm-pipeline.sh -m diploid -r 5 genome_v0.fasta /mnt/2bbc297d-81e9-42f8-8787-0530048638aa/genome_HiC_reads/docker-lachesis/cleaned_bam/FDHC192083078_rep1.bam

/home/hin175/soft/3d-dna/run-asm-pipeline.sh -m diploid -r 5 genome_v0.fasta /mnt/2bbc297d-81e9-42f8-8787-0530048638aa/genome_HiC_reads/docker-lachesis/cleaned_bam/FDHC192083078_rep1.bam
version: 180922
 -m|--mode flag was triggered. Running in diploid mode.
 -r|--rounds flag was triggered, will run 5 round(s) of misjoin correction.
/home/hin175/soft/3d-dna/run-asm-pipeline.sh: line 656: [: too many arguments
/home/hin175/soft/3d-dna/run-asm-pipeline.sh: line 656: [: genome_v0.mnd.0.txt: binary operator expected
###############
Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome_v0.0.cprops
...Using merged_nodups file: genome_v0.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 0 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome_v0.0.asm_mnd.txt does not exist or does not contain any reads.
...detecting misjoins in round 0 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
cat: mismatch_narrow.at.step.0.bed: No such file or directory
cat: repeats_wide.at.step.0.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.1.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 1 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome_v0.1.cprops
...Using merged_nodups file: genome_v0.mnd.1.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 1 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome_v0.1.asm_mnd.txt does not exist or does not contain any reads.
...detecting misjoins in round 1 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
cat: mismatch_narrow.at.step.1.bed: No such file or directory
cat: repeats_wide.at.step.1.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.2.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 2 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome_v0.2.cprops
...Using merged_nodups file: genome_v0.mnd.2.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 2 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome_v0.2.asm_mnd.txt does not exist or does not contain any reads.
...detecting misjoins in round 2 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
cat: mismatch_narrow.at.step.2.bed: No such file or directory
cat: repeats_wide.at.step.2.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.3.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 3 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome_v0.3.cprops
...Using merged_nodups file: genome_v0.mnd.3.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 3 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome_v0.3.asm_mnd.txt does not exist or does not contain any reads.
...detecting misjoins in round 3 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
cat: mismatch_narrow.at.step.3.bed: No such file or directory
cat: repeats_wide.at.step.3.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.4.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 4 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome_v0.4.cprops
...Using merged_nodups file: genome_v0.mnd.4.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 4 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome_v0.4.asm_mnd.txt does not exist or does not contain any reads.
...detecting misjoins in round 4 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
cat: mismatch_narrow.at.step.4.bed: No such file or directory
cat: repeats_wide.at.step.4.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.5.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 5 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: genome_v0.5.cprops
...Using merged_nodups file: genome_v0.mnd.5.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 5 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
temp.genome_v0.5.asm_mnd.txt does not exist or does not contain any reads.
:( No resolved files are found. Please rerun the pipeline to include the scaffold segment. Exiting!

Thanks in advance, Damien

**Comment by dudcha** [comment]
Hi Damien,

Looks like you are trying to use bam as input. 3d-dna cannot work with bam but requires merged_nodups.txt file as second argument, a type of pairwise read alignment catalog produced by Juicer.

Thanks,
Olga
