### ISSUE TITLE
How can I make a mnd.txt format file

### ISSUE THREAD

**Issue by yyx8671** [aidenlab/3d-dna#8]
Hi, 
I want to use your software but I don't know how to create a mnd.txt format file. Can you please give a help? 
Besides, is this software suitable for polyploidy?
Many thanks,
Andy

**Comment by dudcha** [comment]
Hi Andy,

You would need to run our juicer pipeline: https://github.com/theaidenlab/juicer

I suggest to start with a Wiki: https://github.com/theaidenlab/juicer/wiki.

With best wishes,
Olga

**Comment by yyx8671** [comment]
Thanks so much for your reply.
Cheers,
Andy
