### ISSUE TITLE
Ambiguous  errors

### ISSUE THREAD

**Issue by egoltsman** [aidenlab/3d-dna#82]
Hello,
My 3ddna run fails to complete, throwing what looks like a fatal error in the process.  I would expect the run to terminate at the point where the log says 'Exiting', yet, it continues on through the next scaffolding iteration and finally dies with " No resolved files are found".  There are intermediate hic files produced in the output directory, jut not the final "resolved.hic".  Please help me understand what's happening.

```
/global/projectb/sandbox/plant/tools/cori-cle7/software/3d-dna/2796c3b/run-asm-pipeline.sh -i 15000 -q 30 -r 1 canu.FG7.contigs.fasta aligned/merged_nodups.txt
 -i|--input flag was triggered, filtering draft contigs/scaffolds smaller than 15000.
 -q|--mapq flag was triggered, scaffolding using reads with at least 30 mapping quality.
 -r|--rounds flag was triggered, will run 1 round(s) of misjoin correction.
###############
Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 30 threshold mapping quality
...Using cprops file: canu.FG7.contigs.0.cprops
...Using merged_nodups file: canu.FG7.contigs.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
...Starting iteration # 2
.....
.....
...Starting iteration # 395
:) DONE!
...visualizing round 1 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 30 threshold mapping quality
:) -i flag was triggered, building mapq without
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
/global/projectb/sandbox/plant/tools/cori-cle7/software/3d-dna/2796c3b/visualize/run-asm-visualizer.sh: line 185: [: ==: unary operator expected
pre -q 30 -r 2500000,1000000,500000,250000,100000,50000,25000,10000,5000,1000 temp.canu.FG7.contigs.1.asm_mnd.txt canu.FG7.contigs.1_30.hic /dev/fd/63
Not including fragment map
Start preprocess
Writing header
Writing body
..
Writing footer

Finished preprocess
HiC file version: 8

Calculating norms for zoom BP_2500000
Calculating norms for zoom BP_1000000
Calculating norms for zoom BP_500000
Calculating norms for zoom BP_250000
Calculating norms for zoom BP_100000
Calculating norms for zoom BP_50000
Calculating norms for zoom BP_25000
Calculating norms for zoom BP_10000
Calculating norms for zoom BP_5000
Calculating norms for zoom BP_1000
Writing expected
Writing norms
Finished writing norms
:( No resolved files are found. Please rerun the pipeline to include the scaffold segment. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
cat: mismatch_narrow.at.step.0.bed: No such file or directory
cat: repeats_wide.at.step.0.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.1.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 1 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 30 threshold mapping quality
...Using cprops file: canu.FG7.contigs.1.cprops
...Using merged_nodups file: canu.FG7.contigs.mnd.1.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
...Starting iteration # 2
.....
.....
...Starting iteration # 394
...Starting iteration # 395
:) DONE!
...visualizing round 1 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 30 threshold mapping quality
:) -i flag was triggered, building mapq without
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
/global/projectb/sandbox/plant/tools/cori-cle7/software/3d-dna/2796c3b/visualize/run-asm-visualizer.sh: line 185: [: ==: unary operator expected
pre -q 30 -r 2500000,1000000,500000,250000,100000,50000,25000,10000,5000,1000 temp.canu.FG7.contigs.1.asm_mnd.txt canu.FG7.contigs.1_30.hic /dev/fd/63
Not including fragment map
Start preprocess
Writing header
Writing body
..
Writing footer

Finished preprocess
HiC file version: 8

Calculating norms for zoom BP_2500000
Calculating norms for zoom BP_1000000
Calculating norms for zoom BP_500000
Calculating norms for zoom BP_250000
Calculating norms for zoom BP_100000
Calculating norms for zoom BP_50000
Calculating norms for zoom BP_25000
Calculating norms for zoom BP_10000
Calculating norms for zoom BP_5000
Calculating norms for zoom BP_1000
Writing expected
Writing norms
Finished writing norms
:( No resolved files are found. Please rerun the pipeline to include the scaffold segment. Exiting!

```

**Comment by egoltsman** [comment]
p.s.  Just in case, here's the list of versions for some of the core dependencies: 
      PrgEnv-gnu/6.0.5 \                                                                                                                                                                                          
       jdk/1.8.0_202 \                                                                                                                                                                                             
       bwa/0.7.17-11-g20d0a13 \                                                                                                                                                                                    
       python/2.7-anaconda-5.2 \                                                                                                                                                                                   
       3d-dna/2796c3b   

Thank you!

**Comment by dudcha** [comment]
Hi egoltsman,

What's your bash version? Seems like this is causing you trouble (line 185 in run-asm-visualizer.sh):
[ ${ignore_mapq_suffix} == "true" ] && mapqsuf="" || mapqsuf="_"${mapq}
You can go ahead and "" the ignore_mapq_suffix variable.

Thanks,
Olga

**Comment by egoltsman** [comment]
Hi,
Here's the output of bash --version
GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)

**Comment by dudcha** [comment]
Hi Eugene,
Go ahead and add quotes in that line 185 of the script [ ${ignore_mapq_suffix} == "true" ]  -> [ "${ignore_mapq_suffix}" == "true" ] and let me know if it solves things for you.
Thanks, -Olga

**Comment by egoltsman** [comment]
Hi Olga,
I think there's a typo causing an uninitialized variable issue.  The variable was initialized as ignore_mapq_suffix=false on line 49 but the script attempts to set ignore_q_suffix=true on line 184.

**Comment by dudcha** [comment]
It is doing that because you are trying to run with -q 30, so the flag for ignoring suffix gets triggered, correctly so.

**Comment by egoltsman** [comment]
Right, but the typo in the code is causing bash to croak on the uninitialized variable **ignore_q_suffix** when it should be setting **ignore_mapq_suffix**

**Comment by dudcha** [comment]
[_scratching head_], here's what I see as line 184: [ $mapq -eq 1 ] && ignore_mapq_suffix=true ## lab convention to keep mapq 1 wo suffix, otherwise add suffix in case building multiple maps. This is in run-asm-visualizer, here: https://github.com/theaidenlab/3d-dna/blob/master/visualize/run-asm-visualizer.sh. Where do you see the typo? Is this in some older version?

**Comment by dudcha** [comment]
Alright, I found the line you refer to in one of the old commits, though seems like it was fixed some time ago. I recommend using the latest commits. Thanks! -Olga

**Comment by egoltsman** [comment]
Ah, so sorry about that! I'll get the latest. 
Thanks!
