### ISSUE TITLE
error in run-asm-pipeline.sh 

### ISSUE THREAD

**Issue by JierongWang** [aidenlab/3d-dna#85]
Hi ,
I ran 3d-dna for a fungal genome with the command: ./run-asm-pipeline.sh -r 2 fh140.pilon2.fasta aligned/merged_nodups.txt

I got error infomation as follows: awk: /stor9000/apps/users/NWSUAF/2010110076/software/3d-dna/edit/overlay-edits.awk:27: (FILENAME=fh140.pilon2.0_asm.scaffold_track.txt FNR=2) fatal: division by zero attempted

Do you know how I deal with the problem?
Thank you very much!

**Comment by dudcha** [comment]
Hello JRW-ang,

Sorry, this by itself does not give me much to go on with. I don't remember seeing any errors from overlay-edits. Are you using the latest version? Is this the only error message?

Olga

**Comment by JierongWang** [comment]
Thank you so much! I re-downloaded the latest version, and the probelm have been solved.

**Comment by dudcha** [comment]
Great! Good luck with your assembly. Best, -Olga
