### ISSUE TITLE
How to get chr-by-chr heatmap figure?

### ISSUE THREAD

**Issue by forrwill** [aidenlab/3d-dna#86]
After running the pipeline, I get a chromosome-level genome,  and then,  I want to get a chromosome-by-chromosome heatmap figure, what should I do to get it? Is there any tools exists to do it much more easily

**Comment by dudcha** [comment]
Hello,

Right now you will have to rerun Juicer, creating a chrom.sizes file from the new reference etc.

In the next release you will be able to do it without realignment.

Best,
Olga
