### ISSUE TITLE
generate-sorted-cprops-file.awk run error

### ISSUE THREAD

**Issue by shiyi-pan** [aidenlab/3d-dna#88]
Hi，when I run the 3d-dna, I got an error like that:

/ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh -r 2 /ds3512/home/panyp/Hi-C/juicer_data/draft.fasta /ds3512/home/panyp/Hi-C/juicer_data/aligned/merged_nodups.txt
version: 180922
 -r|--rounds flag was triggered, will run 2 round(s) of misjoin correction.
awk: /ds3512/home/panyp/ruanjian/3d-dna/utils/generate-sorted-cprops-file.awk:15: fatal: 3 is invalid as number of arguments for asorti
/ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh: line 634: 1 +  / 2100000000 : syntax error: operand expected (error token is "/ 2100000000 ")
/ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh: line 635: [: -ne: unary operator expected
/ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh: line 656: [: draft.0.cprops: binary operator expected

Can you help me fix the problem?Thank you very much!

**Comment by dudcha** [comment]
Hello Shiyi-Pan,

Judging by the error, perhaps your awk version is not up to date.

Best,
Olga

**Comment by shiyi-pan** [comment]
thank you for your reply, Olga. I updata my awk version and it works . but I met another condition called 'binary operator expected'  :

/ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh -r 2 /ds3512/home/panyp/Hi-C/juicer_data/draft.fasta /ds3512/home/panyp/Hi-C/juicer_data/aligned/merged_nodups.txt
version: 180922
 -r|--rounds flag was triggered, will run 2 round(s) of misjoin correction.
/ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh: line 656: [: draft.0.cprops: binary operator expected
###############
Starting iterating scaffolding with editing:

I don't know the meaning of it and the script still running now. should I worry about it or just let it go ?

**Comment by dudcha** [comment]
Hello Shiyi-Pan,

Check your bash version and double check that you gave proper permissions set for fasta to be read.

Best,
Olga

**Comment by shiyi-pan** [comment]
Thank you for your reply , Olga.  the problem was gone somehow .I don't kown why , i  just found out all the shell scripts that used the sort with --parallel option and deleted the --parallel option because I also met the problem like that :
...Using cprops file: draft.resolved.polish.cprops
...Using merged_nodups file: draft.resolved.polish.mnd.txt
...Explicit scaffold set has been listed as input. Using set as a first iteration.
...Starting iteration # 1
sort: unrecognized option '--parallel=48'
Try `sort --help' for more information.

thank you very much.

**Comment by dudcha** [comment]
See readme for Utils version and make sure your system meets them.
