### ISSUE TITLE
the final genome is twice bigger than original genome

### ISSUE THREAD

**Issue by shiyi-pan** [aidenlab/3d-dna#89]
Hi,when I run the 3d-dna as follows:
 /ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh -r 2 /ds3512/home/panyp/Hi-C/juicer_data/draft.fasta /ds3512/home/panyp/Hi-C/juicer_data/aligned/merged_nodups.txt.
I found the final genome is almost twice bigger than original genome and so is the contigs number.here is the part of the logs:
[dna_3d.sh.o26048.txt](https://github.com/theaidenlab/3d-dna/files/5198842/dna_3d.sh.o26048.txt)
 can you tell my why and help me fix this problem? 
thank you very much.

**Comment by shiyi-pan** [comment]
> Hi,when I run the 3d-dna as follows:
> /ds3512/home/panyp/ruanjian/3d-dna/run-asm-pipeline.sh -r 2 /ds3512/home/panyp/Hi-C/juicer_data/draft.fasta /ds3512/home/panyp/Hi-C/juicer_data/aligned/merged_nodups.txt.
> I found the final genome is almost twice bigger than original genome and so is the contigs number.here is the part of the logs:
> dna_3d.sh.o26048.txt
> can you tell my why and help me fix this problem?
> thank you very much.

**Comment by dudcha** [comment]
Please print stats from the draft and from the FINAL.fasta as generated by 3d-dna/supp/print-n50.awk. Also check for carriage return characters. Thanks, -Olga

**Comment by shiyi-pan** [comment]
Thank you for your reply. I thought it maybe because my bash version is too low to use sort --parallel option. now I'm trying to fix it and figure out whether it works.Thank you very much.
