### ISSUE TITLE
The pipeline could be  used for other species genome assembly?

### ISSUE THREAD

**Issue by liufuyan2016** [aidenlab/3d-dna#9]
I have assemble one genome(plant genome).Could I use the pipeline for chromome assembly?

**Comment by dudcha** [comment]
Hi!

Thanks for your interest. Yes, you can use this pipeline for genome assembly. We recommend using it in combination with Juicebox Assembly Tools (see https://www.biorxiv.org/content/early/2018/01/28/254797 and aidenlab.org/assembly).

Best,
Olga
--
Olga Dudchenko, PhD
M&H Genetics/Aiden Lab
Baylor College of Medicine
