### ISSUE TITLE
How can I skip the ‘ polish‘’ and ‘split’ step and just cluster and order raw contigs ?

### ISSUE THREAD

**Issue by JiaoLaboratory** [aidenlab/3d-dna#90]
hello，
I am using 3DDNA to  perform contig scaffolding,
I just need to cluster and order my contig like 'Lachesis', and don't want to do any polish or split 
Which parameter should I use ?

I try to use '-r 0'  parameter,
'$ 3d-dna/run-asm-pipeline.sh -r 0 --sort-output   references/draft.fasta   merged_nodups.txt  '
But still got polish.hic and split.hic and a final corrected scaffolds.（that is not my required）

I also tried to use '--early-exit' ,
'$  3d-dna/run-asm-pipeline.sh  --early-exit  references/draft.fasta   merged_nodups.txt  ' 
but did not get a final.fasta file

I want to skip the ‘ polish‘’ and ‘split’ step and just cluster and order raw contigs  .
colud U help  me?

@sanjitsbatra @dudcha @theaidenlab

**Comment by dudcha** [comment]
Hello,

Please note that there is no separate clustering step in 3d-dna. If you want to get the first step only which is ordering and orienting the draft sequences you can use the early exit flag.

Olga
