### ISSUE TITLE
Assembly file contains multiple entries of the same contig. Assembly file does not match cprops file. Exiting!

### ISSUE THREAD

**Issue by LILIHAN-001** [aidenlab/3d-dna#94]
Hello，

I extracted some fragements to re-run 3D-DNA pipeline with defalut parameter. The total size of the fragments is 1.7Mb, and the merge_nodups.txt file is 9M. I noticed the FINAL.fasta is about two fold of my initial fragment size and this change happens on the polished step, because the fragments are shown in double in the .asm file. 

raw fragments:
Gap(N) (bp):	199
Total length (bp):	1787750

FINAL fasta:
Gap(N) (bp):	14398
Total length (bp):	3589500

By the way, bash version is >= 4 , and running without parallel has no effect on results.

Here is my command:
bash ~/software/3d-dna/run-asm-pipeline.sh 00.data/genome.fasta 00.data/gm_W_mnd.txt

`:( Assembly file contains multiple entries of the same contig. Exiting!
:( Assembly file contains multiple entries of the same contig. Exiting!
:( Assembly file does not match cprops file. Exiting!
:( Assembly file does not match cprops file. Exiting!
Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=~/04.W_hic/tmp/ -XX:ParallelGCThreads=1
temp.genome.polished.split.asm_mnd.txt does not exist or does not contain any reads.
mv: cannot stat 'genome.polished.split.hic': No such file or directory
:| Warning: no explicit bundle size was listed. Will use the same one as listed for false positive size threshold: this is the most typical scenario.
:| WARNING: GNU Parallel version 20150322 or later not installed. We highly recommend to install it to increase performance. Starting pipeline without parallelization!
:| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
:| Warning: No input for label2 was provided. Default for label2 is ":::debris"
Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=~/04.W_hic/tmp/ -XX:ParallelGCThreads=1
:| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
:| Warning: No input for label2 was provided. Default for label2 is ":::debris"
tail: invalid number of bytes: '+'`

Thanks

Li

**Comment by dudcha** [comment]
Hi Li,

I've missed this, sorry.

This is not some standard complaint: looks like something specific to your input. It seems to be unhappy with your fasta, suggesting that you have duplicated sequences there. What does your .0.cprops file look like? Does it have repeat entries?
Olga
