### ISSUE TITLE
Controlling the number of jobs run in parallel

### ISSUE THREAD

**Issue by rmarquezp** [aidenlab/3d-dna#95]
Hello, 

Is there a way to control the number of jobs run by GNU parallel throughout the pipeline? Looking at some of the code it seems like using 80% of the available CPUs is hard coded into the pipeline. If this is correct would it be possible to add an argument that controls the --jobs flag? Having a hard-coded number of jobs can be inconvenient in some situations, such as  users on shared machines/cluster nodes. 

Thanks!

**Comment by dudcha** [comment]
Hi rmarquezp,

Yes, that's the right flag. We recognize the need and will try to address in one of the future releases.

Best,
Olga

**Comment by rmarquezp** [comment]
Great, thank you very much :-)!
